// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in UaiTrampo worker profile: name, city, state, PIX key, pontua\xE7\xE3o (career score) and CPF status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "nome_completo, cidade, estado, estado_civil, data_nascimento, chave_pix, cpf, pontuacao, user_type, created_at"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Perfil n\xE3o encontrado." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-available-services.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_available_services_default = defineTool2({
  name: "list_available_services",
  title: "List available services",
  description: "List active UaiTrampo services (di\xE1rias) the signed-in worker can apply to. Optionally filter by city or category and limit results.",
  inputSchema: {
    cidade: z.string().optional().describe("Filter by city name (case-sensitive match)."),
    categoria: z.string().optional().describe("Filter by service category."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cidade, categoria, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("servicos").select(
      "id, titulo, descricao, categoria, cidade, estado, data_servico, horario, valor, requisitos, empresa_nome, empresa_pontuacao"
    ).eq("ativo", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (cidade) query = query.eq("cidade", cidade);
    if (categoria) query = query.eq("categoria", categoria);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: data && data.length ? JSON.stringify(data, null, 2) : "Nenhum servi\xE7o dispon\xEDvel no momento com esses filtros."
        }
      ],
      structuredContent: { services: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-my-candidaturas.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_candidaturas_default = defineTool3({
  name: "list_my_candidaturas",
  title: "List my applications",
  description: "List the signed-in worker's UaiTrampo applications (candidaturas), with status, approval and check-in info, plus the linked service title.",
  inputSchema: {
    status: z2.string().optional().describe("Optional status filter (e.g. pendente, aprovada, recusada).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("candidaturas").select(
      "id, status, aprovada_pela_empresa, aprovada_em, chegada_confirmada_em, checkin_em, expediente_encerrado_em, cidade, bairro, created_at, servico_id, servicos!inner(titulo, categoria, data_servico, horario, valor, empresa_nome)"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: data && data.length ? JSON.stringify(data, null, 2) : "Voc\xEA ainda n\xE3o tem candidaturas."
        }
      ],
      structuredContent: { candidaturas: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-my-career.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_career_default = defineTool4({
  name: "get_my_career",
  title: "Get my career stats",
  description: "Return the signed-in worker's UaiTrampo career summary: pontua\xE7\xE3o, total applications, approved, completed shifts and last 5 ratings received.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const userId = ctx.getUserId();
    const [profileRes, candidaturasRes, avaliacoesRes] = await Promise.all([
      supabase.from("profiles").select("nome_completo, pontuacao").eq("user_id", userId).maybeSingle(),
      supabase.from("candidaturas").select("status, aprovada_pela_empresa, expediente_encerrado_em").eq("user_id", userId),
      supabase.from("avaliacoes").select("estrelas, justificativa, tipo, pontos, created_at").eq("trabalhador_id", userId).eq("tipo", "empresa_para_trabalhador").order("created_at", { ascending: false }).limit(5)
    ]);
    if (profileRes.error) {
      return { content: [{ type: "text", text: profileRes.error.message }], isError: true };
    }
    const candidaturas = candidaturasRes.data ?? [];
    const summary = {
      nome: profileRes.data?.nome_completo ?? null,
      pontuacao: profileRes.data?.pontuacao ?? 0,
      total_candidaturas: candidaturas.length,
      aprovadas: candidaturas.filter((c) => c.aprovada_pela_empresa).length,
      concluidas: candidaturas.filter((c) => c.expediente_encerrado_em).length,
      ultimas_avaliacoes: avaliacoesRes.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ltseidxietneylhrhhxm";
var mcp_default = defineMcp({
  name: "uaitrampo-mcp",
  title: "UaiTrampo",
  version: "0.1.0",
  instructions: "Ferramentas do UaiTrampo (plataforma de di\xE1rias). Use get_my_profile para dados do trabalhador logado, list_available_services para vagas ativas, list_my_candidaturas para acompanhar candidaturas e get_my_career para pontua\xE7\xE3o e hist\xF3rico de avalia\xE7\xF5es. Todas as a\xE7\xF5es rodam como o usu\xE1rio conectado, respeitando as permiss\xF5es do banco.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_available_services_default, list_my_candidaturas_default, get_my_career_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
